name: Build Sway for Ubuntu
on: 
  push:
    paths:
      - 'docker/**'
      - 'recipes/sway/**'
    
jobs:
  build_containers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sourcecode
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v18.7
        with:
          files: |
            docker/jameswalmsley/swaybuilder-ubuntu/**

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          username: ${{ secrets.JAMES_DOCKER_HUB_USERNAME }}
          password: ${{ secrets.JAMES_DOCKER_HUB_PASSWORD }}

      - name: Build swaybuilder-ubuntu:20.04
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: docker/build-push-action@v2
        with:
          context: docker/jameswalmsley/swaybuilder-ubuntu
          file: docker/jameswalmsley/swaybuilder-ubuntu/ubuntu-20.04.Dockerfile
          push: true
          tags: jameswalmsley/swaybuilder-ubuntu:20.04

      - name: Build swaybuilder-ubuntu:18.04
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: docker/build-push-action@v2
        with:
          context: docker/jameswalmsley/swaybuilder-ubuntu
          file: docker/jameswalmsley/swaybuilder-ubuntu/ubuntu-18.04.Dockerfile
          push: true
          tags: jameswalmsley/swaybuilder-ubuntu:18.04

  build_20_04:
    runs-on: [self-hosted, Linux, x64]
    container: jameswalmsley/swaybuilder-ubuntu:20.04
    needs: build_containers
    steps:
      - run: "echo Checking out ${{ github.ref }}"
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build Sway
        run: |
          export SUDO=
          export CONFIG_PACKAGE=y
          apt-get -y update
          DEBIAN_FRONTEND=noninteractive apt-get -y install build-essential make
          DEBIAN_FRONTEND=noninteractive apt-get -y install git python3-pip cmake pkg-config
          make sway_defconfig
          make pip-install
          make deb-install
          make source-checkout -j$(nproc)
          make -j$(nproc)
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - uses: actions/upload-artifact@v3
        with:
          name: sway-ubuntu-20-04
          path: out/sway/*.tar.gz

  build_18_04:
    runs-on: [self-hosted, Linux, x64]
    container: jameswalmsley/swaybuilder-ubuntu:18.04
    needs: build_containers
    steps:
      - run: "echo Checking out ${{ github.ref }}"
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build Sway
        run: |
          export SUDO=
          export CONFIG_PACKAGE=y
          apt-get -y update
          DEBIAN_FRONTEND=noninteractive apt-get -y install build-essential make
          DEBIAN_FRONTEND=noninteractive apt-get -y install git python3-pip cmake pkg-config
          make sway_defconfig
          make pip-install
          make deb-install
          make source-checkout -j$(nproc)
          make -j$(nproc)
      - run: echo "🍏 This job's status is ${{ job.status }}."
      - uses: actions/upload-artifact@v3
        with:
          name: sway-ubuntu-18-04
          path: out/sway/*.tar.gz

  release_sway:
    needs: [build_20_04, build_18_04]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        if: startsWith(github.ref, 'refs/tags/sway')

      - run: ls -R
        if: startsWith(github.ref, 'refs/tags/sway')

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/sway')
        with:
          files: |
            */*.tar.gz
